const ProductsData = [
  {
    id: '1',
    title: 'Stainless Steel Mixing Bowls',
    description:
      'Set of 3 stainless steel mixing bowls with non-slip silicone bottoms.',
    category: 'Kitchen Utensils',
    imgUrl: 'img/Stainless Steel Mixing Bowls.jpg',
    price: 29.99,
    brand: 'KitchenAid',
    inStock: 15,
  },
  {
    id: '2',
    title: 'Non-Stick Frying Pan',
    description: '12-inch non-stick frying pan with heat-resistant handle.',
    category: 'Kitchen Utensils',
    imgUrl: 'img/Non-Stick Frying Pan.jpg',
    price: 39.99,
    brand: 'T-fal',
    inStock: 8,
  },
  {
    id: '3',
    title: 'Electric Kettle',
    description: '1.7L electric kettle with rapid boil technology.',
    category: 'Home Appliances',
    imgUrl: 'img/Electric Kettle.jpg',
    price: 24.99,
    brand: 'Hamilton Beach',
    inStock: 12,
  },
  {
    id: '4',
    title: 'Food Processor',
    description: '10-cup food processor with multiple attachments.',
    category: 'Home Appliances',
    imgUrl: 'img/Food Processor.jpg',
    price: 79.99,
    brand: 'Cuisinart',
    inStock: 5,
  },
  {
    id: '5',
    title: 'Cutting Board Set',
    description: 'Set of 3 bamboo cutting boards in different sizes.',
    category: 'Kitchen Utensils',
    imgUrl: 'img/Cutting Board Set.jpg',
    price: 19.99,
    brand: 'Vitamix',
    inStock: 20,
  },
  {
    id: '6',
    title: 'Toaster',
    description: '2-slice toaster with adjustable browning settings.',
    category: 'Home Appliances',
    imgUrl: 'img/Toaster.webp',
    price: 34.99,
    brand: 'Black+Decker',
    inStock: 10,
  },
  {
    id: '7',
    title: 'Knife Set',
    description: 'Set of 6 stainless steel knives with wooden block.',
    category: 'Cooking service',
    imgUrl: 'img/Knife Set.webp',
    price: 49.99,
    brand: 'Vitamix',
    inStock: 15,
  },
  {
    id: '8',
    title: 'Coffee Maker',
    description: '12-cup programmable coffee maker with glass carafe.',
    category: 'Cooking service',
    imgUrl: 'img/Coffee Maker.webp',
    price: 59.99,
    brand: 'Mr. Coffee',
    inStock: 7,
  },
  {
    id: '9',
    title: 'Mixing Spoons',
    description: 'Set of 4 silicone mixing spoons in different colors.',
    category: 'Kitchen Utensils',
    imgUrl: 'img/Mixing Spoons.webp',
    price: 12.99,
    brand: 'KitchenAid',
    inStock: 18,
  },
  {
    id: '10',
    title: 'Blender',
    description: 'High-speed blender with multiple blending modes.',
    category: 'Home Appliances',
    imgUrl: 'img/Blender.webp',
    price: 89.99,
    brand: 'Vitamix',
    inStock: 3,
  },
  {
    id: '11',
    title: 'Measuring Cups and Spoons Set',
    description: 'Set of 8 stainless steel measuring cups and spoons.',
    category: 'Cooking service',
    imgUrl: 'img/Measuring Cups and Spoons Set.webp',
    price: 14.99,
    brand: 'Vitamix',
    inStock: 22,
  },
  {
    id: '12',
    title: 'Rice Cooker',
    description:
      '5-cup rice cooker with steaming basket and non-stick inner pot.',
    category: 'Home Appliances',
    imgUrl: 'img/Rice Cooker.webp',
    price: 49.99,
    brand: 'Nordic Ware',
    inStock: 9,
  },
  {
    id: '13',
    title: 'Baking Sheet Set',
    description: 'Set of 3 non-stick baking sheets in different sizes.',
    category: 'Kitchen Utensils',
    imgUrl: 'img/Baking Sheet Set.webp',
    price: 24.99,
    brand: 'Nordic Ware',
    inStock: 14,
  },
  {
    id: '14',
    title: 'Air Fryer',
    description:
      '5.8-quart air fryer with digital display and multiple cooking presets.',
    category: 'Cooking service',
    imgUrl: 'img/Air Fryer.webp',
    price: 79.99,
    brand: 'Nordic Ware',
    inStock: 6,
  },
  {
    id: '15',
    title: 'Utensil Set',
    description:
      'Set of 10 stainless steel cooking utensils with silicone handles.',
    category: 'Kitchen Utensils',
    imgUrl: 'img/Utensil Set.webp',
    price: 39.99,
    brand: 'KitchenAid',
    inStock: 17,
  },
  {
    id: '16',
    title: 'Hand Mixer',
    description: '5-speed hand mixer with multiple attachments.',
    category: 'Home Appliances',
    imgUrl: 'img/Hand Mixer.webp',
    price: 29.99,
    brand: 'KitchenAid',
    inStock: 11,
  },
  {
    id: '17',
    title: 'Knife Sharpener',
    description: 'Electric knife sharpener with 3-stage sharpening system.',
    category: 'Kitchen Utensils',
    imgUrl: 'img/Knife Sharpener.webp',
    price: 19.99,
    brand: "Chef'sChoice",
    inStock: 13,
  },
  {
    id: '18',
    title: 'Slow Cooker',
    description: '6-quart programmable slow cooker with digital timer.',
    category: 'Home Appliances',
    imgUrl: 'img/Slow Cooker.webp',
    price: 49.99,
    brand: 'Crock-Pot',
    inStock: 8,
  },
  {
    id: '19',
    title: 'Can Opener',
    description: 'Electric can opener with smooth edge cutting mechanism.',
    category: 'Kitchen Utensils',
    imgUrl: 'img/Can Opener.webp',
    price: 14.99,
    brand: 'Hamilton Beach',
    inStock: 16,
  },
  {
    id: '20',
    title: 'Juicer',
    description: 'Centrifugal juicer with wide feed chute and pulp container.',
    category: 'Home Appliances',
    imgUrl: 'img/Juicer.webp',
    price: 69.99,
    brand: 'Breville',
    inStock: 4,
  },
]
export default ProductsData
